version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: translation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - translation_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - translation_network

  # Uncomment to run pgAdmin for database management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - translation_network

volumes:
  postgres_data:

networks:
  translation_network:
    driver: bridge
